[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "7e7gwxgmK7CpeQrnB21XcXgUCt15AGCQuexR2ic4Qkso"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/antoniomartino/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
